---
- hosts: 172.31.34.186
  become: yes
  tasks:
  - name: i want to install apache in ubuntu
    apt: 
      name: apache2
      state: present
      
  -   name: i want to start the apache2
      service: 
        name: apache2
        enabled: yes
        start: started