---
- hosts: 172.31.34.186
  become: yes
  tasks: 
  - name: i want to install command in ubuntu machine.
    command: hostname -f
    register: myvar01

  - name: i want to display the task 1 result
    debug:
      msg: "{{myvar01}}"
  
  - name: I want to install git
    apt: 
      name: git
      state: absent
    when: myvar01.stderr ==""

  - name: i want to install tree in ubuntu.
    apt: 
      name: tree
      state: present
    when: myvar01.stderr ==""
