---
- hosts: 172.31.34.186
  become: yes
  tasks:
  - name: i want to install git
    apt:
      name: git
      state: absent
    
  - name: i want to install apache2
    apt: 
      name: apache2
      state: absent

  - name: i want to install tree
    apt: 
      name: tree
      state: absent

