---
- hosts: all
  become: yes
  tasks:
    - name: I want to install apache2 in  both groups
      apt: 
        - name: apache2
          state: present
      when :  ansible_os_family == "Debian"
    - name: I want to start the apache2 in both groups
      service:  
        - name: apache2
          state: restarted
      when :  ansible_os_family == "Debian"
    - name: I want to start the httpd in both groups
      yum:  
        - name: httpd
          state: present
      when :  ansible_os_family == "RedHat"
    - name: I want to start the apache2 in both groups
      service:  
        - name: apache2
          state: restarted
      when :  ansible_os_family == "RedHat"
