---

- name: Download tomcat gip file
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5.tar.gz
    dest: /tmp/apache-tomcat-8.5.5.tar.gz
    force_basic_auth: yes

- name: create directory
  file:
    path: /opt/tomcat
    state: directory
    
- name: extract and copy the tomcat file
  command:
    cmd: sudo tar xzvf /tmp/apache-tomcat-8.5.5.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENCE

    
 