---
- get_url:
    url: https://get.jenkins.io/war/2.327/jenkins.war
    dest: /tmp/jenkins.war
    force_basic_auth: yes

- name: example copying file with owner and permissions
  become: yes
  copy:
    src: /tmp/jenkins.war
    dest: /opt/tomcat/apache-tomcat-8.5.5/webapps
    remote_src: yes
   